# lock-threads (https://github.com/marketplace/actions/lock-threads)
name: Lock threads

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  discussions: write

jobs:
  lock:
  # if: github.repository == 'netbox-community/netbox' # 조건문 삭제
    runs-on: ubuntu-latest
    steps:
    # - uses: dessant/lock-threads@1bf7ec25051fe7c00bdd17e6a7cf3d7bfb7dc771 # v5.0.1
      - uses: dessant/lock-threads@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.0.1+
        with:
          issue-inactive-days: 90
          pr-inactive-days: 30
          discussion-inactive-days: 180
          issue-lock-reason: 'resolved'
