name: Update translation strings

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  LOCALE: "en"

jobs:
  makemessages:
    if: github.repository == 'netbox-community/netbox'
    runs-on: ubuntu-latest
    env:
      NETBOX_CONFIGURATION: netbox.configuration_testing

    steps:
    - name: Create app token
      uses: actions/create-github-app-token@f07f7f756721ebd886c2462646a35f78a8bc4de #v1
      id: app-token
      with:
        app-id: 1076524
        private-key: ${{ secrets.HOUSEKEEPING_SECRET_KEY }}

    - name: Check out repo
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 #v4
      with:
          token: ${{ steps.app-token.outputs.token }}

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 #v5
      with:
        python-version: 3.11

    - name: Install system dependencies
      run: sudo apt install -y gettext

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run makemessages
      run: python netbox/manage.py makemessages -l ${{ env.LOCALE }}

    - name: Commit changes
      uses: EndBug/add-and-commit@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.1.4+
      with:
        add: 'netbox/translations/'
        default_author: github_actions
        message: 'Update source translation strings'
